#!/usr/bin/env bash

set -e

# Get the current folder name
current_dir=$(basename "$PWD")

# Determine what to add based on folder
if [ "$current_dir" = "auto" ]; then
	echo "Detected 'auto/' folder. Adding parent repo files..."
	echo
	git add ..
else
	echo "Adding current folder files..."
	echo
	git add .
fi

# Show status
git status
