#!/usr/bin/env bash

set -e

for d in */; do
	if [ -d "$d/.git" ]; then
		echo "======== /$d ========"
		echo
		(
			cd "$d"
			git add .
			git status | grep -v '^$'
		)
		echo
	fi
done

wait

echo "======== All Repositories Displayed ========"
