#!/usr/bin/env bash

set -e

# This is used for the Hang at the end, for disabling it.
SCRIPT_PATH=$(readlink -f "${BASH_SOURCE[0]}")

# Ensure $HOME exists
if [ -z "$HOME" ]; then
	echo "❌ HOME variable not set!"
	exit 1
fi

# Parse arguments
AUTHOR="$1"
REPO="$2"
CLONE_METHOD="$3"

# Echo provided arguments
[ -n "$AUTHOR" ] && echo "Author to clone (GitHub username): $AUTHOR"
[ -n "$REPO" ] && echo "Repository to clone (Repository name): $REPO"
[ -n "$CLONE_METHOD" ] && echo "Clone method (ssh/HTTPS): $CLONE_METHOD"

# Prompt if not provided
if [ -z "$AUTHOR" ]; then
	read -rp "Author to clone (GitHub username): " AUTHOR
fi

if [ -z "$REPO" ]; then
	read -rp "Repository to clone (Repository name): " REPO
fi

if [ -z "$CLONE_METHOD" ]; then
	read -rp "Clone method (ssh/HTTPS): " CLONE_METHOD
fi

echo

CLONE_METHOD=${CLONE_METHOD,,}

# Set clone prefix
if [ "$CLONE_METHOD" = "ssh" ]; then
	CLONE_PREFIX="git@github.com:"
	CLONE_METHOD=SSH
else
	CLONE_PREFIX="https://github.com/"
	CLONE_METHOD=HTTPS
fi

# Setup target directory
ROOT_DIR="$HOME/GitHub"
AUTHOR_DIR="$ROOT_DIR/$AUTHOR"
mkdir -p "$AUTHOR_DIR"
cd "$AUTHOR_DIR"

# Clone or update the repo
if [ -d "$REPO/.git" ]; then
	echo "ℹ️  Updating $REPO using $CLONE_METHOD..."
	cd "$REPO" && git pull --quiet || echo "❌ Pulling $REPO failed"
else
	echo "ℹ️  Cloning $REPO using $CLONE_METHOD..."
	git clone --quiet "${CLONE_PREFIX}${AUTHOR}/${REPO}.git" || echo "❌ Cloning $REPO failed"
fi

echo
echo "✅ Clone/update task completed!"

# Hang

KEEP_OPEN=false

if [ "$KEEP_OPEN" = true ]; then
	echo
	read -p "Press 'Enter' to exit / Type 'disable' to disable hanging (local only): " response
	if [ "$response" = "disable" ]; then
		sed -i 's/^KEEP_OPEN=true/KEEP_OPEN=false/' "$SCRIPT_PATH"
		echo
		echo "KEEP_OPEN set to false"
		echo "Change 'KEEP_OPEN=true' to enable"
		echo
		for i in {5..1}; do
			echo -n "Exiting in $i..."
			sleep 1
			echo -ne "\r"
		done
		echo "Exiting now.        "
	fi
fi
